# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Programming for Biologists
tagline:          'A Jekyll theme'
description:      'Teaching biologists the tools they need to use computers to do cool science'
url:              http://www.progbio.org
baseurl:          /

author:
  name:           'Ethan White'
  url:            https://twitter.com/ethanwhite

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ethanwhite/progbio
