# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Ecology in an Era of Big Data
description:      'Teaching the tools to get computers to do cool science'
url:              https://albertl.github.io/ecology-data
baseurl:          /ecology-data
email:            loren.albert@mail.wvu.edu
feedbackurl:      https://forms.gle/YiFWDpbYKfMEv4Hj6
author:
  name:           'Loren Albert'
  url:            https://www.leavestoecosystems.com/

github:
  repo:           https://github.com/Albertl/ecology-data
  #               Be sure the 'Issues' feature is activated in 'Settings'
