# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Data Carpentry -for- Biologists
tagline:          'A Jekyll theme'
description:      'Teaching biologists the tools they need to use computers to do cool science'
url:              http://www.datacarpentry.org
baseurl:          /semester-biology

author:
  name:           'Ethan White'
  url:            https://twitter.com/ethanwhite

github:
  repo:           https://github.com/datacarpentry/semester-biology
